### ISSUE TITLE
SDK wont controll all Leds in a System.

### ISSUE THREAD

**Issue by KBhamm** [CorsairOfficial/cue-sdk#11] opened 2020-07-29 18:59 UTC
I use the wallpaperengine beta which uses the newest SDK version v3.0.355. It only controlls 4 and a half LL120 and the strips on the same Node pro second channel arent controlled.  Everytime the same leds. Sometimes it works after a restart. Sometimes not.

**Comment by intrueder** [comment] 2020-08-05 10:51
Hey, @KBhamm 
I am curious what is going on with your setup, because I cannot reproduce the issue on my side.
Can you confirm that you are using the latest version of iCUE? Do you have any other RGB software running?

**Comment by elsalakk** [comment] 2020-08-06 23:04
I am developing RGB support for an application of mine, and I run into this issue. 
Doing a quick deep dive it looks like CorsairGetLedPositionsByDeviceIndex() returns 150 LEDs for my lightning node controller.
CorsairGetDeviceInfo() returns the channels object, which shows that the lightning node supports 204 LEDS.

I have 5 QL fans, so I should have 170LEDs (5*34), so for some reason 20 leds are dropped, which causes half a fan to not be lit with the effect. I am not sure if this is caused by a limit of 150 per device or what exactly, but clearly a bug in the API.

**Comment by Legion2** [comment] 2020-08-06 23:07
@elsalakk do you use the latest iCUE version?

**Comment by elsalakk** [comment] 2020-08-06 23:22
Yes, I updated iCUE last night, but I am running on an older version of the SDK (3.0.234) Latest one available for c# https://github.com/AndrewBabbitt97/CUESDK.NET, so perhaps this is the issue, I am not sure if  wallpaperengine is written in C#, but if it is, then maybe that is the issue on that side too.

**Comment by elsalakk** [comment] 2020-08-07 00:33
Yeah, just dropping the 3.0.355 dll in place of the older one, fixes the QL fan issue, so maybe the pepes over at wallpaper engine could do the same, this issue can be safely closed.

**Comment by KBhamm** [comment] 2020-08-07 12:34
The Developer at WPE directed me to here because its a well known bug and he already runs on the latest SDK with an LED limit of 300 per Channel. It is only on like every second boot or so. sometimes all 5 LL120 and the Strips work and sometimes only 4 and a half and no Strip. But these are everytime the same. All firmwares are up to date.

**Comment by intrueder** [comment] 2020-08-20 16:54
@KBhamm, has this been fixed in Wallpaper Engine 1.3.75?
Some users report that everything is working well now: https://forum.corsair.com/v3/showthread.php?t=195638

**Comment by Legion2** [comment] 2020-08-20 19:36
I have two LS100 one on a monitor the other on my desk. The on the monitor has 84 leds and the on the desk 135. Depending on the order iCUE detects these, Wallpaper Engine only controls the first 84 leds of the 135 leds on my desk.

**Comment by KBhamm** [comment] 2020-08-20 20:45
> @KBhamm, has this been fixed in Wallpaper Engine 1.3.75?
> Some users report that everything is working well now: https://forum.corsair.com/v3/showthread.php?t=195638

Its strange it works only on roughly every second boot. sometimes all Leds but like this moment 4 Led stripes and 1.5LL120 is not light up.

**Comment by Legion2** [comment] 2020-08-20 21:10
@KBhamm I think this is related to what I have described in my previous comment.

**Comment by KBhamm** [comment] 2020-08-30 08:44
> @KBhamm I think this is related to what I have described in my previous comment.

That might be but on my systems everytime the same leds arent controlled.

**Comment by Legion2** [comment] 2020-08-30 09:40
Yes it's the same for me. The last 51 LEDs of the 135 aren't controlled

**Comment by intrueder** [comment] 2020-09-29 10:08
Hey @KBhamm 
Is this problem reproducible only on system boot? Will all LEDs be controlled if WPE is restarted?

**Comment by intrueder** [comment] 2020-10-22 18:36
Hi there,
please, check the latest beta version of WallpaperEngine (v1.3.176 or higher), it should address the issue.

**Comment by intrueder** [comment] 2020-10-29 14:14
I am closing this because the issue was on the WPE side

**Closed by intrueder** 2020-10-29 14:14 UTC

**Comment by Legion2** [comment] 2020-10-29 16:06
I can not confirm that it is fixed because with the current iCUE version the LS100 doesn't work well.
