### ISSUE TITLE
Dark Core Pro RGB support

### ISSUE THREAD

**Issue by hugarburdur** [CorsairOfficial/cue-sdk#18] opened 2021-01-28 15:05 UTC
The current SDK version doesn't support the Dark Core RGB Pro mouse.
Could it be added?
The resulting issue is that iCUE SDK won't initialize when I use the Dark Core (wired or wireless) while I also use a perfectly compatible K95 keyboard. Would it be possible to at least _ignore_ the unsupported devices to let the SDK initialize with the other compatible devices in iCUE?

**Comment by intrueder** [comment] 2021-02-02 19:41
> The resulting issue is that iCUE SDK won't initialize when I use the Dark Core (wired or wireless) while I also use a perfectly compatible K95 keyboard.

I cannot confirm this behavior.
If a device is not supported, the SDK ignores it.

Can you share a code snippet or provide iCUE logs?

**Comment by hugarburdur** [comment] 2021-02-08 08:39
Hi Tymur,
Thanks for the reply.
Please find the iCue log for today. I started the SDK client at 09:32.

The code used by my client is quite simple :
CueSDK.Initialize();

This returns the following exception when Dark Core RGB is plugged-in : « EX: Can't initial mouse with layout '0' »

I’m surprised that you can’t confirm this behavior, as the CueSDK.Initialize() method has the Following comment in the SDK :
        // Exceptions :
        //   T:CUE.NET.Exceptions.WrapperException:
        //     Thrown if the SDK is already initialized, the SDK is not compatible to CUE or
        //     if CUE returns unknown devices.

I hope this can help.

Thomas


De : Tymur Mudzhyri<mailto:notifications@github.com>
Envoyé le :mardi 2 février 2021 20:42
À : CorsairOfficial/cue-sdk<mailto:cue-sdk@noreply.github.com>
Cc : hugarburdur<mailto:hugar@live.fr>; Author<mailto:author@noreply.github.com>
Objet :Re: [CorsairOfficial/cue-sdk] Dark Core Pro RGB support (#18)


The resulting issue is that iCUE SDK won't initialize when I use the Dark Core (wired or wireless) while I also use a perfectly compatible K95 keyboard.

I cannot confirm this behavior.
If a device is not supported, the SDK ignores it.

Can you share a code snippet or provide iCUE logs?

**Comment by intrueder** [comment] 2021-02-08 11:58
Well, it means that you are using https://github.com/DarthAffe/CUE.NET, and the problem is there.
By the way, it's readme suggests you to try a newer library: https://github.com/DarthAffe/RGB.NET

I'm closing this as unrelated to the CUESDK project.

**Closed by intrueder** 2021-02-08 11:58 UTC
