### ISSUE TITLE
No devices detected, due to PC going to lock; fixed by restarting iCue

### ISSUE THREAD

**Issue by andyman1222** [CorsairOfficial/cue-sdk#28] opened 2022-07-28 10:06 UTC
I am running the latest SDK version. I have an h100i and an Asus motherboard, both which show up in iCue. I have a program using the SDK running in the background, when I lock my PC (win+L). While in the lock screen, my cooler goes into its hardware lighting mode. 

Upon logging back in, the lighting goes back to software mode. All the lights on the water cooler turn off, while the lights on the motherboard remain unchanged. With the program still active, I cannot change the lights within iCue, until I close my program (as my program is running in exclusive mode). Upon restarting my program, CorsairGetDeviceCount returns 0, and CorsairGetDeviceInfo does not return any info for my two devices.

Upon quitting out of iCue (not restarting the service or disabling/enabling plugins) and reopening, CorsairGetDeviceCount returns 2, as expected, and CorsairGetDeviceInfo retrieves both devices as expected.

**Comment by intrueder** [comment] 2022-08-15 10:30
Thanks, @andyman1222
The issue is on iCUE side and not related to the SDK.
I'll close this issue once it is fixed in iCUE.

**Comment by intrueder** [comment] 2022-09-19 13:59
Fixed in iCUE 4.28

**Closed by intrueder** 2022-09-19 13:59 UTC
